### ISSUE TITLE
BUG: Not replacing menus for logged in non-menus.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-nav-menus#11]
https://github.com/strangerstudios/pmpro-nav-menus/blob/fc47d8b879f5c1bcf769181e3e31c7278b3bd6bb/pmpro-nav-menus.php#L101-L104

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/bug-in-pmpro-nav-menus-add-on/?skipped

**Comment by Gazzamit** [comment]
Removing the above code allows the code to continue correctly and process the code below.

//for logged in non-members
	if( is_user_logged_in() && !pmpro_hasMembershipLevel() ){
		//let's replace with certain menu
		foreach ($menus as $location => $description)
		{
			if(($location == "pmpro-non-members-" . $args['theme_location']) && 
					has_nav_menu("pmpro-non-members-" . $args['theme_location']) )
			{	
				$args['theme_location'] = $location;
				break;
			}
		
		}
	}

Adding in a simple echo statement before the break shows that the code above works as the echo appears in the menu of a logged in non member. However, when you add in pages using standard theme menu customisation they do not appear.

**Comment by dparker1005** [comment]
Bug fixed in v.3.4
