### ISSUE TITLE
"Click here to set menus for specific levels" does not reveal menu settings for levels

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-nav-menus#20]
When a user clicks on the link "Click here to set menus for specific levels" nothing happens.

To replicate:

1. Navigate to Appearance > Widgets
2. Click to expand the Pages section and click on `+` symbol to add a widget block.
3. Click on Browse all and click on PMPro - Custom Membership Menu.
4. In the block for Custom Membership Menu click on "Click here to set menus for specific levels"

**Comment by ipokkel** [comment]
**Moderators Only:** https://www.paidmembershipspro.com/forums/topic/difficulties-configuring-nav-menu-add-on/

**Comment by andrewlimaza** [comment]
Installing the "Classic Widgets" plugin solves this issue (for now) - https://wordpress.org/plugins/classic-widgets/
